# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/intel/cube_iwork8ultimate/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/atomisp/00ov2680.aiqb:system/etc/atomisp/00ov2680.aiqb \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/atomisp/01ov2680.aiqb:system/etc/atomisp/01ov2680.aiqb \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/camera3_profiles.xml:system/etc/camera3_profiles.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/AudioParameterFramework.xml:system/etc/parameter-framework/AudioParameterFramework.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml:system/etc/parameter-framework/Settings/Audio/AudioConfigurableDomains.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/Settings/Route/RouteConfigurableDomains.xml:system/etc/parameter-framework/Settings/Route/RouteConfigurableDomains.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/Structure/Audio/AudioClass.xml:system/etc/parameter-framework/Structure/Audio/AudioClass.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/Structure/Audio/NUVOTON_NAU88L24Subsystem.xml:system/etc/parameter-framework/Structure/Audio/NUVOTON_NAU88L24Subsystem.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/Structure/Audio/SstSubsystem.xml:system/etc/parameter-framework/Structure/Audio/SstSubsystem.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/parameter-framework/Structure/Route/RouteSubsystem.xml:system/etc/parameter-framework/Structure/Route/RouteSubsystem.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/sensor_hal_config_default.xml:system/etc/sensor_hal_config_default.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/etc/tuning/audio/layout_probes.xml:system/etc/tuning/audio/layout_probes.xml \
    vendor/intel/cube_iwork8ultimate/proprietary/lib/hw/camera.gmin.so:system/lib/hw/camera.gmin.so \
    vendor/intel/cube_iwork8ultimate/proprietary/lib/hw/sensors.gmin.so:system/lib/hw/sensors.gmin.so
